package com.global.meter.v3.common.enums;

import java.util.AbstractMap.SimpleEntry;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import com.global.meter.v3.utils.DivFactorConstants;

public enum DivFactorPropertyDataSet {
	IHM_1PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.IHM_1PH_INSTANTANEOUSREAD),
	IHM_3PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.IHM_3PH_INSTANTANEOUSREAD),
	IHM_1PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.IHM_1PH_DAILYLOADPROFILE),
	IHM_3PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.IHM_3PH_DAILYLOADPROFILE),
	IHM_1PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.IHM_1PH_DELTALOADPROFILE),
	IHM_3PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.IHM_3PH_DELTALOADPROFILE),
	IHM_1PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.IHM_1PH_BILLINGDATA),
	IHM_3PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.IHM_3PH_BILLINGDATA),
	IHM_1PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.IHM_1PH_CURRENTRELATEDEVENTS),
	IHM_3PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.IHM_3PH_CURRENTRELATEDEVENTS),
	IHM_1PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.IHM_1PH_OTHERRELATEDEVENTS),
	IHM_3PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.IHM_3PH_OTHERRELATEDEVENTS),
	IHM_3PH_VOLTAGERELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.IHM_3PH_VOLTAGERELATEDEVENTS),
	JPM_1PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.JPM_1PH_INSTANTANEOUSREAD),
	JPM_3PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.JPM_3PH_INSTANTANEOUSREAD),
	JPM_1PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.JPM_1PH_DAILYLOADPROFILE),
	JPM_3PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.JPM_3PH_DAILYLOADPROFILE),
	JPM_1PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.JPM_1PH_DELTALOADPROFILE),
	JPM_3PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.JPM_3PH_DELTALOADPROFILE),
	JPM_1PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.JPM_1PH_BILLINGDATA),
	JPM_3PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.JPM_3PH_BILLINGDATA),
	JPM_1PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.JPM_1PH_CURRENTRELATEDEVENTS),
	JPM_3PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.JPM_3PH_CURRENTRELATEDEVENTS),
	JPM_1PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.JPM_1PH_OTHERRELATEDEVENTS),
	JPM_3PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.JPM_3PH_OTHERRELATEDEVENTS),
	JPM_3PH_VOLTAGERELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.JPM_3PH_VOLTAGERELATEDEVENTS),
	FLA_1PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.FLA_1PH_INSTANTANEOUSREAD),
	FLA_3PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.FLA_3PH_INSTANTANEOUSREAD),
	FLA_1PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.FLA_1PH_DAILYLOADPROFILE),
	FLA_3PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.FLA_3PH_DAILYLOADPROFILE),
	FLA_1PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.FLA_1PH_DELTALOADPROFILE),
	FLA_3PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.FLA_3PH_DELTALOADPROFILE),
	FLA_1PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.FLA_1PH_BILLINGDATA),
	FLA_3PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.FLA_3PH_BILLINGDATA),
	FLA_1PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.FLA_1PH_CURRENTRELATEDEVENTS),
	FLA_3PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.FLA_3PH_CURRENTRELATEDEVENTS),
	FLA_1PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.FLA_1PH_OTHERRELATEDEVENTS),
	FLA_3PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.FLA_3PH_OTHERRELATEDEVENTS),
	FLA_3PH_VOLTAGERELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.FLA_3PH_VOLTAGERELATEDEVENTS),
	ALLIED_1PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.ALLIED_1PH_INSTANTANEOUSREAD),
	ALLIED_V5_62_1PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.ALLIED_V5_62_1PH_INSTANTANEOUSREAD),
	ALLIED_AW3_30_1PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.ALLIED_AW3_30_1PH_INSTANTANEOUSREAD),
	ALLIED_AW3_09_1PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.ALLIED_AW3_09_1PH_INSTANTANEOUSREAD),
	ALLIED_AW3_31_1PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.ALLIED_AW3_31_1PH_INSTANTANEOUSREAD),
	ALLIED_3PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.ALLIED_3PH_INSTANTANEOUSREAD),
	ALLIED_1PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.ALLIED_1PH_DAILYLOADPROFILE),
	ALLIED_AW3_31_1PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.ALLIED_AW3_31_1PH_DAILYLOADPROFILE),
	ALLIED_V5_62_1PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.ALLIED_V5_62_1PH_DAILYLOADPROFILE),
	ALLIED_3PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.ALLIED_3PH_DAILYLOADPROFILE),
	ALLIED_1PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.ALLIED_1PH_DELTALOADPROFILE),
	ALLIED_AW3_31_1PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.ALLIED_AW3_31_1PH_DELTALOADPROFILE),
	ALLIED_V5_62_1PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.ALLIED_V5_62_1PH_DELTALOADPROFILE),
	ALLIED_3PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.ALLIED_3PH_DELTALOADPROFILE),
	ALLIED_1PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.ALLIED_1PH_BILLINGDATA),
	ALLIED_AW3_31_1PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.ALLIED_AW3_31_1PH_BILLINGDATA),
	ALLIED_V5_62_1PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.ALLIED_V5_62_1PH_BILLINGDATA),
	ALLIED_3PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.ALLIED_3PH_BILLINGDATA),
	ALLIED_1PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.ALLIED_1PH_CURRENTRELATEDEVENTS),
	ALLIED_V5_62_1PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.ALLIED_V5_62_1PH_CURRENTRELATEDEVENTS),
	ALLIED_3PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.ALLIED_3PH_CURRENTRELATEDEVENTS),
	ALLIED_1PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.ALLIED_1PH_OTHERRELATEDEVENTS),
	ALLIED_V5_62_1PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.ALLIED_V5_62_1PH_OTHERRELATEDEVENTS),
	ALLIED_3PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.ALLIED_3PH_OTHERRELATEDEVENTS),
	ALLIED_3PH_VOLTAGERELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.ALLIED_3PH_VOLTAGERELATEDEVENTS),
	LECS_1PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.LECS_1PH_INSTANTANEOUSREAD),
	LECS_3PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.LECS_3PH_INSTANTANEOUSREAD),
	LECS_1PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.LECS_1PH_DAILYLOADPROFILE),
	LECS_3PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.LECS_3PH_DAILYLOADPROFILE),
	LECS_1PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.LECS_1PH_DELTALOADPROFILE),
	LECS_3PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.LECS_3PH_DELTALOADPROFILE),
	LECS_1PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.LECS_1PH_BILLINGDATA),
	LECS_3PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.LECS_3PH_BILLINGDATA),
	LECS_1PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.LECS_1PH_CURRENTRELATEDEVENTS),
	LECS_3PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.LECS_3PH_CURRENTRELATEDEVENTS),
	LECS_1PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.LECS_1PH_OTHERRELATEDEVENTS),
	LECS_3PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.LECS_3PH_OTHERRELATEDEVENTS),
	LECS_3PH_VOLTAGERELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.LECS_3PH_VOLTAGERELATEDEVENTS),
	CPS_1PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.CPS_1PH_INSTANTANEOUSREAD),
	CPS_3PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.CPS_3PH_INSTANTANEOUSREAD),
	CPS_1PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.CPS_1PH_DAILYLOADPROFILE),
	CPS_3PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.CPS_3PH_DAILYLOADPROFILE),
	CPS_1PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.CPS_1PH_DELTALOADPROFILE),
	CPS_3PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.CPS_3PH_DELTALOADPROFILE),
	CPS_1PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.CPS_1PH_BILLINGDATA),
	CPS_3PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.CPS_3PH_BILLINGDATA),
	CPS_1PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.CPS_1PH_CURRENTRELATEDEVENTS),
	CPS_3PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.CPS_3PH_CURRENTRELATEDEVENTS),
	CPS_1PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.CPS_1PH_OTHERRELATEDEVENTS),
	CPS_3PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.CPS_3PH_OTHERRELATEDEVENTS),
	CPS_3PH_VOLTAGERELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.CPS_3PH_VOLTAGERELATEDEVENTS),
	CPS_CT_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.CPS_CT_INSTANTANEOUSREAD),
	CPS_CT_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.CPS_CT_DAILYLOADPROFILE),
	CPS_CT_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.CPS_CT_DELTALOADPROFILE),
	CPS_CT_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.CPS_CT_BILLINGDATA),
	CPS_CT_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.CPS_CT_CURRENTRELATEDEVENTS),
	CPS_CT_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.CPS_CT_OTHERRELATEDEVENTS),
	CPS_CT_VOLTAGERELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.CPS_CT_VOLTAGERELATEDEVENTS),
	ZEN_1PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.ZEN_1PH_INSTANTANEOUSREAD),
	ZEN_1PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.ZEN_1PH_DAILYLOADPROFILE),
	ZEN_1PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.ZEN_1PH_DELTALOADPROFILE),
	ZEN_1PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.ZEN_1PH_BILLINGDATA),
	ZEN_1PH_VOLTAGERELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.ZEN_1PH_VOLTAGERELATEDEVENTS),
	ZEN_1PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.ZEN_1PH_CURRENTRELATEDEVENTS),
	ZEN_1PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.ZEN_1PH_OTHERRELATEDEVENTS),
	ZEN_3PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.ZEN_3PH_INSTANTANEOUSREAD),
	ZEN_3PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.ZEN_3PH_DAILYLOADPROFILE),
	ZEN_3PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.ZEN_3PH_DELTALOADPROFILE),
	ZEN_3PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.ZEN_3PH_BILLINGDATA),
	ZEN_3PH_VOLTAGERELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.ZEN_3PH_VOLTAGERELATEDEVENTS),
	ZEN_3PH_CURRENTRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.ZEN_3PH_CURRENTRELATEDEVENTS),
	ZEN_3PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.ZEN_3PH_OTHERRELATEDEVENTS),
	HPL_1PH_INSTANTANEOUSREAD(DivFactorConstants.DivFactorPropertyName.HPL_1PH_INSTANTANEOUSREAD),
	HPL_1PH_DAILYLOADPROFILE(DivFactorConstants.DivFactorPropertyName.HPL_1PH_DAILYLOADPROFILE),
	HPL_1PH_DELTALOADPROFILE(DivFactorConstants.DivFactorPropertyName.HPL_1PH_DELTALOADPROFILE),
	HPL_1PH_BILLINGDATA(DivFactorConstants.DivFactorPropertyName.HPL_1PH_BILLINGDATA),
	HPL_1PH_OTHERRELATEDEVENTS(DivFactorConstants.DivFactorPropertyName.HPL_1PH_OTHERRELATEDEVENTS)
	;

	public String propertyKey;

	private DivFactorPropertyDataSet(String propertyKey) {
		this.propertyKey = propertyKey;
	}

	public static final Map<Object, String> DivFactorProperty = Stream.of(
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_1PH_INSTANTANEOUSREAD,
					"IHM_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_INSTANTANEOUSREAD,
					"IHM_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_1PH_DAILYLOADPROFILE,
					"IHM_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_DAILYLOADPROFILE,
					"IHM_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_1PH_DELTALOADPROFILE,
					"IHM_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_DELTALOADPROFILE,
					"IHM_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_1PH_BILLINGDATA, "IHM_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_BILLINGDATA, "IHM_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_1PH_CURRENTRELATEDEVENTS,
					"IHM_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_CURRENTRELATEDEVENTS,
					"IHM_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_1PH_OTHERRELATEDEVENTS,
					"IHM_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_OTHERRELATEDEVENTS,
					"IHM_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_VOLTAGERELATEDEVENTS,
					"IHM_3ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_1PH_INSTANTANEOUSREAD,
					"JPM_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_INSTANTANEOUSREAD,
					"JPM_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_1PH_DAILYLOADPROFILE,
					"JPM_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_DAILYLOADPROFILE,
					"JPM_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_1PH_DELTALOADPROFILE,
					"JPM_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_DELTALOADPROFILE,
					"JPM_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_1PH_BILLINGDATA, "JPM_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_BILLINGDATA, "JPM_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_1PH_CURRENTRELATEDEVENTS,
					"JPM_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_CURRENTRELATEDEVENTS,
					"JPM_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_1PH_OTHERRELATEDEVENTS,
					"JPM_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_OTHERRELATEDEVENTS,
					"JPM_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_VOLTAGERELATEDEVENTS,
					"JPM_3ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_1PH_INSTANTANEOUSREAD,
					"FLA_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_INSTANTANEOUSREAD,
					"FLA_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_1PH_DAILYLOADPROFILE,
					"FLA_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_DAILYLOADPROFILE,
					"FLA_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_1PH_DELTALOADPROFILE,
					"FLA_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_DELTALOADPROFILE,
					"FLA_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_1PH_BILLINGDATA, "FLA_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_BILLINGDATA, "FLA_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_1PH_CURRENTRELATEDEVENTS,
					"FLA_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_CURRENTRELATEDEVENTS,
					"FLA_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_1PH_OTHERRELATEDEVENTS,
					"FLA_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_OTHERRELATEDEVENTS,
					"FLA_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_VOLTAGERELATEDEVENTS,
					"FLA_3ph_VoltageRelatedEvents"),

			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_1PH_INSTANTANEOUSREAD,
					"ALLIED_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_V5_62_1PH_INSTANTANEOUSREAD,
					"ALLIED_V5.62_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_AW3_30_1PH_INSTANTANEOUSREAD,
					"ALLIED_AW3.30_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_AW3_09_1PH_INSTANTANEOUSREAD,
					"ALLIED_AW3.09_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_AW3_31_1PH_INSTANTANEOUSREAD,
					"ALLIED_AW3.31_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_INSTANTANEOUSREAD,
					"ALLIED_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_1PH_DAILYLOADPROFILE,
					"ALLIED_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_AW3_31_1PH_DAILYLOADPROFILE,
					"ALLIED_AW3.31_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_V5_62_1PH_DAILYLOADPROFILE,
					"ALLIED_V5.62_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_DAILYLOADPROFILE,
					"ALLIED_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_1PH_DELTALOADPROFILE,
					"ALLIED_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_AW3_31_1PH_DELTALOADPROFILE,
					"ALLIED_AW3.31_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_V5_62_1PH_DELTALOADPROFILE,
					"ALLIED_V5.62_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_DELTALOADPROFILE,
					"ALLIED_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_1PH_BILLINGDATA, "ALLIED_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_AW3_31_1PH_BILLINGDATA,
					"ALLIED_AW3.31_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_V5_62_1PH_BILLINGDATA,
					"ALLIED_V5.62_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_BILLINGDATA, "ALLIED_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_1PH_CURRENTRELATEDEVENTS,
					"ALLIED_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_V5_62_1PH_CURRENTRELATEDEVENTS,
					"ALLIED_V5.62_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_CURRENTRELATEDEVENTS,
					"ALLIED_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_1PH_OTHERRELATEDEVENTS,
					"ALLIED_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_V5_62_1PH_OTHERRELATEDEVENTS,
					"ALLIED_V5.62_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_OTHERRELATEDEVENTS,
					"ALLIED_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_VOLTAGERELATEDEVENTS,
					"ALLIED_3ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_1PH_INSTANTANEOUSREAD,
					"LECS_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_INSTANTANEOUSREAD,
					"LECS_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_1PH_DAILYLOADPROFILE,
					"LECS_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_DAILYLOADPROFILE,
					"LECS_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_1PH_DELTALOADPROFILE,
					"LECS_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_DELTALOADPROFILE,
					"LECS_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_1PH_BILLINGDATA, "LECS_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_BILLINGDATA, "LECS_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_1PH_CURRENTRELATEDEVENTS,
					"LECS_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_CURRENTRELATEDEVENTS,
					"LECS_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_1PH_OTHERRELATEDEVENTS,
					"LECS_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_OTHERRELATEDEVENTS,
					"LECS_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_VOLTAGERELATEDEVENTS,
					"LECS_3ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_1PH_INSTANTANEOUSREAD,
					"CPS_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_INSTANTANEOUSREAD,
					"CPS_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_1PH_DAILYLOADPROFILE,
					"CPS_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_DAILYLOADPROFILE,
					"CPS_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_1PH_DELTALOADPROFILE,
					"CPS_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_DELTALOADPROFILE,
					"CPS_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_1PH_BILLINGDATA, "CPS_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_BILLINGDATA, "CPS_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_1PH_CURRENTRELATEDEVENTS,
					"CPS_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_CURRENTRELATEDEVENTS,
					"CPS_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_1PH_OTHERRELATEDEVENTS,
					"CPS_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_OTHERRELATEDEVENTS,
					"CPS_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_VOLTAGERELATEDEVENTS,
					"CPS_3ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_INSTANTANEOUSREAD,
					"CPS_ct_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_DAILYLOADPROFILE, "CPS_ct_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_DELTALOADPROFILE, "CPS_ct_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_BILLINGDATA, "CPS_ct_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_CURRENTRELATEDEVENTS,
					"CPS_ct_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_OTHERRELATEDEVENTS,
					"CPS_ct_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_VOLTAGERELATEDEVENTS,
					"CPS_ct_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_INSTANTANEOUSREAD,
					"ZEN_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_DAILYLOADPROFILE,
					"ZEN_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_DELTALOADPROFILE,
					"ZEN_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_BILLINGDATA, "ZEN_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_VOLTAGERELATEDEVENTS,
					"ZEN_1ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_CURRENTRELATEDEVENTS,
					"ZEN_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_OTHERRELATEDEVENTS,
					"ZEN_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_INSTANTANEOUSREAD,
					"ZEN_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_DAILYLOADPROFILE,
					"ZEN_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_DELTALOADPROFILE,
					"ZEN_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_BILLINGDATA, "ZEN_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_VOLTAGERELATEDEVENTS,
					"ZEN_3ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_CURRENTRELATEDEVENTS,
					"ZEN_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_OTHERRELATEDEVENTS,
					"ZEN_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.HPL_1PH_INSTANTANEOUSREAD,
					"HPL_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.HPL_1PH_DAILYLOADPROFILE,
					"HPL_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.HPL_1PH_DELTALOADPROFILE,
					"HPL_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.HPL_1PH_BILLINGDATA, "HPL_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.HPL_1PH_OTHERRELATEDEVENTS,
					"HPL_1ph_OtherRelatedEvents")
			)
			.collect(Collectors.toMap(SimpleEntry::getKey, SimpleEntry::getValue));

	public synchronized static boolean contains(String commandName) {

		try {
			for (DivFactorPropertyDataSet c : DivFactorPropertyDataSet.values()) {
				if (c.propertyKey.equals(commandName)) {
					return true;
				}
			}
		} catch (Exception e) {
		}
		return false;
	}

	public static final Map<Object, String> DivFactorPropertyName = Stream.of(
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_1PH_INSTANTANEOUSREAD.propertyKey,
					"IHM_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_INSTANTANEOUSREAD.propertyKey,
					"IHM_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_1PH_DAILYLOADPROFILE.propertyKey,
					"IHM_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_DAILYLOADPROFILE.propertyKey,
					"IHM_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_1PH_DELTALOADPROFILE.propertyKey,
					"IHM_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_DELTALOADPROFILE.propertyKey,
					"IHM_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_1PH_BILLINGDATA.propertyKey, "IHM_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_BILLINGDATA.propertyKey, "IHM_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_1PH_CURRENTRELATEDEVENTS.propertyKey,
					"IHM_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_CURRENTRELATEDEVENTS.propertyKey,
					"IHM_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_1PH_OTHERRELATEDEVENTS.propertyKey,
					"IHM_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_OTHERRELATEDEVENTS.propertyKey,
					"IHM_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.IHM_3PH_VOLTAGERELATEDEVENTS.propertyKey,
					"IHM_3ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_1PH_INSTANTANEOUSREAD.propertyKey,
					"JPM_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_INSTANTANEOUSREAD.propertyKey,
					"JPM_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_1PH_DAILYLOADPROFILE.propertyKey,
					"JPM_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_DAILYLOADPROFILE.propertyKey,
					"JPM_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_1PH_DELTALOADPROFILE.propertyKey,
					"JPM_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_DELTALOADPROFILE.propertyKey,
					"JPM_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_1PH_BILLINGDATA.propertyKey, "JPM_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_BILLINGDATA.propertyKey, "JPM_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_1PH_CURRENTRELATEDEVENTS.propertyKey,
					"JPM_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_CURRENTRELATEDEVENTS.propertyKey,
					"JPM_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_1PH_OTHERRELATEDEVENTS.propertyKey,
					"JPM_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_OTHERRELATEDEVENTS.propertyKey,
					"JPM_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.JPM_3PH_VOLTAGERELATEDEVENTS.propertyKey,
					"JPM_3ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_1PH_INSTANTANEOUSREAD.propertyKey,
					"FLA_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_INSTANTANEOUSREAD.propertyKey,
					"FLA_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_1PH_DAILYLOADPROFILE.propertyKey,
					"FLA_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_DAILYLOADPROFILE.propertyKey,
					"FLA_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_1PH_DELTALOADPROFILE.propertyKey,
					"FLA_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_DELTALOADPROFILE.propertyKey,
					"FLA_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_1PH_BILLINGDATA.propertyKey, "FLA_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_BILLINGDATA.propertyKey, "FLA_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_1PH_CURRENTRELATEDEVENTS.propertyKey,
					"FLA_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_CURRENTRELATEDEVENTS.propertyKey,
					"FLA_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_1PH_OTHERRELATEDEVENTS.propertyKey,
					"FLA_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_OTHERRELATEDEVENTS.propertyKey,
					"FLA_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.FLA_3PH_VOLTAGERELATEDEVENTS.propertyKey,
					"FLA_3ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_1PH_INSTANTANEOUSREAD.propertyKey,
					"ALLIED_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_V5_62_1PH_INSTANTANEOUSREAD,
					"ALLIED_V5_62_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_AW3_30_1PH_INSTANTANEOUSREAD,
					"ALLIED_AW3_30_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_AW3_09_1PH_INSTANTANEOUSREAD,
					"ALLIED_AW3_09_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_AW3_31_1PH_INSTANTANEOUSREAD,
					"ALLIED_AW3_31_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_INSTANTANEOUSREAD,
					"ALLIED_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_1PH_DAILYLOADPROFILE,
					"ALLIED_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_AW3_31_1PH_DAILYLOADPROFILE,
					"ALLIED_AW3_31_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_V5_62_1PH_DAILYLOADPROFILE,
					"ALLIED_V5_62_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_DAILYLOADPROFILE,
					"ALLIED_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_1PH_DELTALOADPROFILE,
					"ALLIED_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_AW3_31_1PH_DELTALOADPROFILE,
					"ALLIED_AW3_31_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_V5_62_1PH_DELTALOADPROFILE,
					"ALLIED_V5_62_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_DELTALOADPROFILE,
					"ALLIED_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_1PH_BILLINGDATA, "ALLIED_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_AW3_31_1PH_BILLINGDATA,
					"ALLIED_AW3_31_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_V5_62_1PH_BILLINGDATA,
					"ALLIED_V5_62_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_BILLINGDATA, "ALLIED_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_1PH_CURRENTRELATEDEVENTS,
					"ALLIED_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_V5_62_1PH_CURRENTRELATEDEVENTS,
					"ALLIED_V5_62_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_CURRENTRELATEDEVENTS,
					"ALLIED_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_1PH_OTHERRELATEDEVENTS,
					"ALLIED_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_V5_62_1PH_OTHERRELATEDEVENTS,
					"ALLIED_V5_62_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_OTHERRELATEDEVENTS,
					"ALLIED_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ALLIED_3PH_VOLTAGERELATEDEVENTS,
					"ALLIED_3ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_1PH_INSTANTANEOUSREAD.propertyKey,
					"LECS_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_INSTANTANEOUSREAD.propertyKey,
					"LECS_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_1PH_DAILYLOADPROFILE.propertyKey,
					"LECS_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_DAILYLOADPROFILE.propertyKey,
					"LECS_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_1PH_DELTALOADPROFILE.propertyKey,
					"LECS_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_DELTALOADPROFILE.propertyKey,
					"LECS_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_1PH_BILLINGDATA.propertyKey, "LECS_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_BILLINGDATA.propertyKey, "LECS_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_1PH_CURRENTRELATEDEVENTS.propertyKey,
					"LECS_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_CURRENTRELATEDEVENTS.propertyKey,
					"LECS_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_1PH_OTHERRELATEDEVENTS.propertyKey,
					"LECS_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_OTHERRELATEDEVENTS.propertyKey,
					"LECS_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.LECS_3PH_VOLTAGERELATEDEVENTS.propertyKey,
					"LECS_3ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_1PH_INSTANTANEOUSREAD.propertyKey,
					"CPS_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_INSTANTANEOUSREAD.propertyKey,
					"CPS_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_1PH_DAILYLOADPROFILE.propertyKey,
					"CPS_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_DAILYLOADPROFILE.propertyKey,
					"CPS_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_1PH_DELTALOADPROFILE.propertyKey,
					"CPS_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_DELTALOADPROFILE.propertyKey,
					"CPS_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_1PH_BILLINGDATA.propertyKey, "CPS_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_BILLINGDATA.propertyKey, "CPS_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_1PH_CURRENTRELATEDEVENTS.propertyKey,
					"CPS_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_CURRENTRELATEDEVENTS.propertyKey,
					"CPS_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_1PH_OTHERRELATEDEVENTS.propertyKey,
					"CPS_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_OTHERRELATEDEVENTS.propertyKey,
					"CPS_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_3PH_VOLTAGERELATEDEVENTS.propertyKey,
					"CPS_3ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_INSTANTANEOUSREAD.propertyKey,
					"CPS_ct_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_DAILYLOADPROFILE.propertyKey, "CPS_ct_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_DELTALOADPROFILE.propertyKey, "CPS_ct_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_BILLINGDATA.propertyKey, "CPS_ct_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_CURRENTRELATEDEVENTS.propertyKey,
					"CPS_ct_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_OTHERRELATEDEVENTS.propertyKey,
					"CPS_ct_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.CPS_CT_VOLTAGERELATEDEVENTS.propertyKey,
					"CPS_ct_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_INSTANTANEOUSREAD.propertyKey,
					"ZEN_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_DAILYLOADPROFILE.propertyKey,
					"ZEN_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_DELTALOADPROFILE.propertyKey,
					"ZEN_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_BILLINGDATA.propertyKey, "ZEN_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_VOLTAGERELATEDEVENTS.propertyKey,
					"ZEN_1ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_CURRENTRELATEDEVENTS.propertyKey,
					"ZEN_1ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_1PH_OTHERRELATEDEVENTS.propertyKey,
					"ZEN_1ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_INSTANTANEOUSREAD.propertyKey,
					"ZEN_3ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_DAILYLOADPROFILE.propertyKey,
					"ZEN_3ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_DELTALOADPROFILE.propertyKey,
					"ZEN_3ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_BILLINGDATA.propertyKey, "ZEN_3ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_VOLTAGERELATEDEVENTS.propertyKey,
					"ZEN_3ph_VoltageRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_CURRENTRELATEDEVENTS.propertyKey,
					"ZEN_3ph_CurrentRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.ZEN_3PH_OTHERRELATEDEVENTS.propertyKey,
					"ZEN_3ph_OtherRelatedEvents"),
			new SimpleEntry<>(DivFactorPropertyDataSet.HPL_1PH_INSTANTANEOUSREAD.propertyKey,
					"HPL_1ph_InstantaneousRead"),
			new SimpleEntry<>(DivFactorPropertyDataSet.HPL_1PH_DAILYLOADPROFILE.propertyKey,
					"HPL_1ph_DailyLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.HPL_1PH_DELTALOADPROFILE.propertyKey,
					"HPL_1ph_DeltaLoadProfile"),
			new SimpleEntry<>(DivFactorPropertyDataSet.HPL_1PH_BILLINGDATA.propertyKey, "HPL_1ph_BillingData"),
			new SimpleEntry<>(DivFactorPropertyDataSet.HPL_1PH_OTHERRELATEDEVENTS.propertyKey,
					"HPL_1ph_OtherRelatedEvents")
			)
			.collect(Collectors.toMap(SimpleEntry::getKey, SimpleEntry::getValue));

	public static String getPropertyKeyByUiName(String fieldName) throws IllegalArgumentException {

		if (DivFactorPropertyName.containsKey(fieldName)) {

			return DivFactorPropertyName.get(fieldName);

		} else {

			throw new IllegalArgumentException("Invalid Property Name: " + fieldName);

		}

	}

}
