##1 Name Plate Logs added 

CREATE TABLE name_plate_logs (
    device_serial_number text,
    mdas_datetime timestamp,
    category text,
    current_ratings text,
    dcu_serial_number text,
    device_id text,
    dt_name text,
    feeder_name text,
    firmware_version text,
    manufacturer_name text,
    manufacturer_year text,
    meter_serial_number text,
    meter_type text,
    owner_name text,
    status text,
    subdevision_name text,
    substation_name text,
    PRIMARY KEY (device_serial_number, mdas_datetime)
)

#2  Devices Command Batch Logs added 
CREATE TABLE devices_commands_batch_logs (
    batch_id text,
    command_name text,
    failure int,
    hier_name text,
    hier_value text,
    in_progress int,
    mdas_datetime timestamp,
    owner_name text,
    success int,
    PRIMARY KEY (batch_id)
)

#3 Device Config Batch Logs added 
CREATE TABLE devices_config_batch_logs (
    batch_id text,
    added int,
    command_name text,
    failure int,
    hier_name text,
    hier_value text,
    in_progress int,
    mdas_datetime timestamp,
    owner_name text,
    success int,
    PRIMARY KEY (batch_id)
)

#4 Devices Config Read Batch Logs
CREATE TABLE devices_config_read_batch_logs (
    batch_id text,
    added int,
    command_name text,
    failure int,
    hier_name text,
    hier_value text,
    in_progress int,
    mdas_datetime timestamp,
    owner_name text,
    success int,
    PRIMARY KEY (batch_id)
) 

#5 Gas Meter Tables added
CREATE TABLE nb_gas_meter_data (
    gasmeterno text,
    hesdatetime timestamp,
    accumulativetotalamount double,
    cellid text,
    checkdomain text,
    controlfields text,
    data text,
    ecl text,
    frameaggrementversion text,
    frameheader text,
    framelength text,
    frametrail text,
    frequencypoint text,
    functioncode text,
    iccid text,
    keyversion text,
    mainelectricvoltage double,
    messageno text,
    meterdatetime timestamp,
    meterlength text,
    meterstate text,
    ownername text,
    protocol text,
    reportmode text,
    signalpower text,
    signalstrength text,
    snr text,
    voltagepercentage double,
    PRIMARY KEY (gasmeterno, hesdatetime)
) 

CREATE TABLE gas_meter_info (
    gas_meter_no text,
    address text,
    consumer_name text,
    created_by text,
    created_on_datetime timestamp,
    creation_date timestamp,
    crn text,
    crn_new text,
    description text,
    dev_mode text,
    device_id text,
    device_type text,
    email_id text,
    installation_datetime timestamp,
    ip_config text,
    ip_port_main text,
    ip_port_push text,
    last_updated_by text,
    last_updated_on_datetime timestamp,
    lastcommunicationdatetime timestamp,
    latitude text,
    longitude text,
    meter_type text,
    modification_date timestamp,
    network text,
    owner_name text,
    payment_mode int,
    phone_number text,
    sim_no text,
    status text,
    version text,
    PRIMARY KEY (gas_meter_no)
)

CREATE TABLE gas_meter_info_history (
    gas_meter_no text,
    address text,
    consumer_name text,
    created_by text,
    created_on_datetime timestamp,
    creation_date timestamp,
    crn text,
    crn_new text,
    description text,
    dev_mode text,
    device_id text,
    device_type text,
    email_id text,
    installation_datetime timestamp,
    ip_config text,
    ip_port_main text,
    ip_port_push text,
    last_updated_by text,
    last_updated_on_datetime timestamp,
    lastcommunicationdatetime timestamp,
    latitude text,
    longitude text,
    meter_type text,
    modification_date timestamp,
    network text,
    owner_name text,
    payment_mode int,
    phone_number text,
    sim_no text,
    status text,
    version text,
    PRIMARY KEY (gas_meter_no)
) 

#6 Added TABLE daily_load_profile_ct

CREATE TABLE daily_load_profile_ct (
    device_serial_number text,
    datetime timestamp,
    cumulative_energy_kvah_export double,
    cumulative_energy_kvah_import double,
    cumulative_energy_kvarh_q1 double,
    cumulative_energy_kvarh_q2 double,
    cumulative_energy_kvarh_q3 double,
    cumulative_energy_kvarh_q4 double,
    cumulative_energy_kwh_export double,
    cumulative_energy_kwh_import double,
    dcu_serial_number text,
    dt_name text,
    feeder_name text,
    maximum_demand_kva double,
    maximum_demand_kva_datetime timestamp,
    maximum_demand_kw double,
    maximum_demand_kw_datetime timestamp,
    maximum_demand_kw_export double,
    maximum_demand_kw_export_datetime timestamp,
    mdas_datetime timestamp,
    meter_datetime timestamp,
    owner_name text,
    subdevision_name text,
    substation_name text,
    PRIMARY KEY (device_serial_number, datetime)
)

#7 Added TABLE event_data_ct
CREATE TABLE event_data_ct (
    device_serial_number text,
    event_code int,
    event_datetime timestamp,
    cumulative_energy_kvah_export double,
    cumulative_energy_kvah_import double,
    cumulative_energy_kwh_export double,
    cumulative_energy_kwh_import double,
    cumulative_tamper_count int,
    current_ib double,
    current_ir double,
    current_iy double,
    dcu_serial_number text,
    dt_name text,
    event_category text,
    event_type text,
    feeder_name text,
    mdas_datetime timestamp,
    meter_datetime timestamp,
    neutral_current double,
    owner_name text,
    power_factor_b_phase double,
    power_factor_r_phase double,
    power_factor_y_phase double,
    subdevision_name text,
    substation_name text,
    voltage_vbn double,
    voltage_vrn double,
    voltage_vyn double,
    PRIMARY KEY (device_serial_number, event_code, event_datetime)
)

#8 Instantaneous CT Table Added
CREATE TABLE instantaneous_data_ct (
    device_serial_number text,
    datetime timestamp,
    active_power_kw double,
    apparent_power_kva double,
    cumm_power_off_duration_in_mins double,
    cumulative_bill_count int,
    cumulative_energy_kvah_export double,
    cumulative_energy_kvah_import double,
    cumulative_energy_kvarh_q1 double,
    cumulative_energy_kvarh_q2 double,
    cumulative_energy_kvarh_q3 double,
    cumulative_energy_kvarh_q4 double,
    cumulative_energy_kwh_export double,
    cumulative_energy_kwh_import double,
    cumulative_program_count int,
    cumulative_tamper_count int,
    dcu_serial_number text,
    dt_name text,
    enable_disable_load int,
    feeder_name text,
    frequency double,
    instant_voltage_l1 double,
    instant_voltage_l2 double,
    instant_voltage_l3 double,
    last_billing_datetime timestamp,
    maximum_demand_kva double,
    maximum_demand_kva_datetime timestamp,
    maximum_demand_kw double,
    maximum_demand_kw_datetime timestamp,
    mdas_datetime timestamp,
    meter_datetime timestamp,
    no_of_power_failure int,
    owner_name text,
    phase_current_l1 double,
    phase_current_l2 double,
    phase_current_l3 double,
    power_factor_3ph double,
    power_factor_l1 double,
    power_factor_l2 double,
    power_factor_l3 double,
    reactive_power_kvar double,
    signed_power_factor_b_phase double,
    subdevision_name text,
    substation_name text,
    tracking_id text,
    load_limit int,
    load_limit_status int,
    PRIMARY KEY (device_serial_number, datetime)
 )
 
#9 Billing Data CT
CREATE TABLE billing_data_ct (
    device_serial_number text,
    billing_datetime timestamp,
    cumulative_energy_kvah_export double,
    cumulative_energy_kvah_export_tier1 double,
    cumulative_energy_kvah_export_tier2 double,
    cumulative_energy_kvah_export_tier3 double,
    cumulative_energy_kvah_export_tier4 double,
    cumulative_energy_kvah_export_tier5 double,
    cumulative_energy_kvah_export_tier6 double,
    cumulative_energy_kvah_export_tier7 double,
    cumulative_energy_kvah_export_tier8 double,
    cumulative_energy_kvah_import double,
    cumulative_energy_kvah_tier1 double,
    cumulative_energy_kvah_tier2 double,
    cumulative_energy_kvah_tier3 double,
    cumulative_energy_kvah_tier4 double,
    cumulative_energy_kvah_tier5 double,
    cumulative_energy_kvah_tier6 double,
    cumulative_energy_kvah_tier7 double,
    cumulative_energy_kvah_tier8 double,
    cumulative_energy_kvarh_lag double,
    cumulative_energy_kvarh_q1 double,
    cumulative_energy_kvarh_q2 double,
    cumulative_energy_kvarh_q3 double,
    cumulative_energy_kvarh_q4 double,
    cumulative_energy_kwh_export double,
    cumulative_energy_kwh_export_tier1 double,
    cumulative_energy_kwh_export_tier2 double,
    cumulative_energy_kwh_export_tier3 double,
    cumulative_energy_kwh_export_tier4 double,
    cumulative_energy_kwh_export_tier5 double,
    cumulative_energy_kwh_export_tier6 double,
    cumulative_energy_kwh_export_tier7 double,
    cumulative_energy_kwh_export_tier8 double,
    cumulative_energy_kwh_import double,
    cumulative_energy_kwh_tier1 double,
    cumulative_energy_kwh_tier2 double,
    cumulative_energy_kwh_tier3 double,
    cumulative_energy_kwh_tier4 double,
    cumulative_energy_kwh_tier5 double,
    cumulative_energy_kwh_tier6 double,
    cumulative_energy_kwh_tier7 double,
    cumulative_energy_kwh_tier8 double,
    dcu_serial_number text,
    dt_name text,
    feeder_name text,
    maximum_demand_kva double,
    maximum_demand_kva_date timestamp,
    maximum_demand_kva_date_export_tier1 timestamp,
    maximum_demand_kva_date_export_tier2 timestamp,
    maximum_demand_kva_date_export_tier3 timestamp,
    maximum_demand_kva_date_export_tier4 timestamp,
    maximum_demand_kva_date_export_tier5 timestamp,
    maximum_demand_kva_date_export_tier6 timestamp,
    maximum_demand_kva_date_export_tier7 timestamp,
    maximum_demand_kva_date_export_tier8 timestamp,
    maximum_demand_kva_export double,
    maximum_demand_kva_export_date timestamp,
    maximum_demand_kva_export_tier1 double,
    maximum_demand_kva_export_tier2 double,
    maximum_demand_kva_export_tier3 double,
    maximum_demand_kva_export_tier4 double,
    maximum_demand_kva_export_tier5 double,
    maximum_demand_kva_export_tier6 double,
    maximum_demand_kva_export_tier7 double,
    maximum_demand_kva_export_tier8 double,
    maximum_demand_kva_tier1 double,
    maximum_demand_kva_tier1_date timestamp,
    maximum_demand_kva_tier2 double,
    maximum_demand_kva_tier2_date timestamp,
    maximum_demand_kva_tier3 double,
    maximum_demand_kva_tier3_date timestamp,
    maximum_demand_kva_tier4 double,
    maximum_demand_kva_tier4_date timestamp,
    maximum_demand_kva_tier5 double,
    maximum_demand_kva_tier5_date timestamp,
    maximum_demand_kva_tier6 double,
    maximum_demand_kva_tier6_date timestamp,
    maximum_demand_kva_tier7 double,
    maximum_demand_kva_tier7_date timestamp,
    maximum_demand_kva_tier8 double,
    maximum_demand_kva_tier8_date timestamp,
    maximum_demand_kw double,
    maximum_demand_kw_date timestamp,
    maximum_demand_kw_date_export_tier1 timestamp,
    maximum_demand_kw_date_export_tier2 timestamp,
    maximum_demand_kw_date_export_tier3 timestamp,
    maximum_demand_kw_date_export_tier4 timestamp,
    maximum_demand_kw_date_export_tier5 timestamp,
    maximum_demand_kw_date_export_tier6 timestamp,
    maximum_demand_kw_date_export_tier7 timestamp,
    maximum_demand_kw_date_export_tier8 timestamp,
    maximum_demand_kw_export double,
    maximum_demand_kw_export_date timestamp,
    maximum_demand_kw_export_tier1 double,
    maximum_demand_kw_export_tier2 double,
    maximum_demand_kw_export_tier3 double,
    maximum_demand_kw_export_tier4 double,
    maximum_demand_kw_export_tier5 double,
    maximum_demand_kw_export_tier6 double,
    maximum_demand_kw_export_tier7 double,
    maximum_demand_kw_export_tier8 double,
    maximum_demand_kw_tier1 double,
    maximum_demand_kw_tier1_date timestamp,
    maximum_demand_kw_tier2 double,
    maximum_demand_kw_tier2_date timestamp,
    maximum_demand_kw_tier3 double,
    maximum_demand_kw_tier3_date timestamp,
    maximum_demand_kw_tier4 double,
    maximum_demand_kw_tier4_date timestamp,
    maximum_demand_kw_tier5 double,
    maximum_demand_kw_tier5_date timestamp,
    maximum_demand_kw_tier6 double,
    maximum_demand_kw_tier6_date timestamp,
    maximum_demand_kw_tier7 double,
    maximum_demand_kw_tier7_date timestamp,
    maximum_demand_kw_tier8 double,
    maximum_demand_kw_tier8_date timestamp,
    mdas_datetime timestamp,
    meter_datetime timestamp,
    owner_name text,
    power_on_duration_mins int,
    subdevision_name text,
    substation_name text,
    system_power_factor_billing_period double,
    tamper_count int,
    PRIMARY KEY (device_serial_number, billing_datetime)
)

#10 Last Billing Data CT
CREATE TABLE last_billing_data_ct (
    device_serial_number text,
    billing_datetime timestamp,
    cumulative_energy_kvah_export double,
    cumulative_energy_kvah_export_tier1 double,
    cumulative_energy_kvah_export_tier2 double,
    cumulative_energy_kvah_export_tier3 double,
    cumulative_energy_kvah_export_tier4 double,
    cumulative_energy_kvah_export_tier5 double,
    cumulative_energy_kvah_export_tier6 double,
    cumulative_energy_kvah_export_tier7 double,
    cumulative_energy_kvah_export_tier8 double,
    cumulative_energy_kvah_import double,
    cumulative_energy_kvah_tier1 double,
    cumulative_energy_kvah_tier2 double,
    cumulative_energy_kvah_tier3 double,
    cumulative_energy_kvah_tier4 double,
    cumulative_energy_kvah_tier5 double,
    cumulative_energy_kvah_tier6 double,
    cumulative_energy_kvah_tier7 double,
    cumulative_energy_kvah_tier8 double,
    cumulative_energy_kvarh_lag double,
    cumulative_energy_kvarh_q1 double,
    cumulative_energy_kvarh_q2 double,
    cumulative_energy_kvarh_q3 double,
    cumulative_energy_kvarh_q4 double,
    cumulative_energy_kwh_export double,
    cumulative_energy_kwh_export_tier1 double,
    cumulative_energy_kwh_export_tier2 double,
    cumulative_energy_kwh_export_tier3 double,
    cumulative_energy_kwh_export_tier4 double,
    cumulative_energy_kwh_export_tier5 double,
    cumulative_energy_kwh_export_tier6 double,
    cumulative_energy_kwh_export_tier7 double,
    cumulative_energy_kwh_export_tier8 double,
    cumulative_energy_kwh_import double,
    cumulative_energy_kwh_tier1 double,
    cumulative_energy_kwh_tier2 double,
    cumulative_energy_kwh_tier3 double,
    cumulative_energy_kwh_tier4 double,
    cumulative_energy_kwh_tier5 double,
    cumulative_energy_kwh_tier6 double,
    cumulative_energy_kwh_tier7 double,
    cumulative_energy_kwh_tier8 double,
    dcu_serial_number text,
    dt_name text,
    feeder_name text,
    maximum_demand_kva double,
    maximum_demand_kva_date timestamp,
    maximum_demand_kva_date_export_tier1 timestamp,
    maximum_demand_kva_date_export_tier2 timestamp,
    maximum_demand_kva_date_export_tier3 timestamp,
    maximum_demand_kva_date_export_tier4 timestamp,
    maximum_demand_kva_date_export_tier5 timestamp,
    maximum_demand_kva_date_export_tier6 timestamp,
    maximum_demand_kva_date_export_tier7 timestamp,
    maximum_demand_kva_date_export_tier8 timestamp,
    maximum_demand_kva_export double,
    maximum_demand_kva_export_date timestamp,
    maximum_demand_kva_export_tier1 double,
    maximum_demand_kva_export_tier2 double,
    maximum_demand_kva_export_tier3 double,
    maximum_demand_kva_export_tier4 double,
    maximum_demand_kva_export_tier5 double,
    maximum_demand_kva_export_tier6 double,
    maximum_demand_kva_export_tier7 double,
    maximum_demand_kva_export_tier8 double,
    maximum_demand_kva_tier1 double,
    maximum_demand_kva_tier1_date timestamp,
    maximum_demand_kva_tier2 double,
    maximum_demand_kva_tier2_date timestamp,
    maximum_demand_kva_tier3 double,
    maximum_demand_kva_tier3_date timestamp,
    maximum_demand_kva_tier4 double,
    maximum_demand_kva_tier4_date timestamp,
    maximum_demand_kva_tier5 double,
    maximum_demand_kva_tier5_date timestamp,
    maximum_demand_kva_tier6 double,
    maximum_demand_kva_tier6_date timestamp,
    maximum_demand_kva_tier7 double,
    maximum_demand_kva_tier7_date timestamp,
    maximum_demand_kva_tier8 double,
    maximum_demand_kva_tier8_date timestamp,
    maximum_demand_kw double,
    maximum_demand_kw_date timestamp,
    maximum_demand_kw_date_export_tier1 timestamp,
    maximum_demand_kw_date_export_tier2 timestamp,
    maximum_demand_kw_date_export_tier3 timestamp,
    maximum_demand_kw_date_export_tier4 timestamp,
    maximum_demand_kw_date_export_tier5 timestamp,
    maximum_demand_kw_date_export_tier6 timestamp,
    maximum_demand_kw_date_export_tier7 timestamp,
    maximum_demand_kw_date_export_tier8 timestamp,
    maximum_demand_kw_export double,
    maximum_demand_kw_export_date timestamp,
    maximum_demand_kw_export_tier1 double,
    maximum_demand_kw_export_tier2 double,
    maximum_demand_kw_export_tier3 double,
    maximum_demand_kw_export_tier4 double,
    maximum_demand_kw_export_tier5 double,
    maximum_demand_kw_export_tier6 double,
    maximum_demand_kw_export_tier7 double,
    maximum_demand_kw_export_tier8 double,
    maximum_demand_kw_tier1 double,
    maximum_demand_kw_tier1_date timestamp,
    maximum_demand_kw_tier2 double,
    maximum_demand_kw_tier2_date timestamp,
    maximum_demand_kw_tier3 double,
    maximum_demand_kw_tier3_date timestamp,
    maximum_demand_kw_tier4 double,
    maximum_demand_kw_tier4_date timestamp,
    maximum_demand_kw_tier5 double,
    maximum_demand_kw_tier5_date timestamp,
    maximum_demand_kw_tier6 double,
    maximum_demand_kw_tier6_date timestamp,
    maximum_demand_kw_tier7 double,
    maximum_demand_kw_tier7_date timestamp,
    maximum_demand_kw_tier8 double,
    maximum_demand_kw_tier8_date timestamp,
    mdas_datetime timestamp,
    meter_datetime timestamp,
    owner_name text,
    power_on_duration_mins int,
    subdevision_name text,
    substation_name text,
    system_power_factor_billing_period double,
    tamper_count int,
    PRIMARY KEY (device_serial_number, billing_datetime)
)

#DeltaLP Three Phase
CREATE TABLE load_profile_data_threephase (
    device_serial_number text,
    avg_signal_strength double,
    b_phase_active_power_kw double,
    block_energy_kvah_export double,
    block_energy_kvah_import double,
    block_energy_kwh_export double,
    block_energy_kwh_import double,
    cumulative_energy_kvah double,
    cumulative_energy_kvarh_q1 double,
    cumulative_energy_kvarh_q2 double,
    cumulative_energy_kvarh_q3 double,
    cumulative_energy_kvarh_q4 double,
    cumulative_energy_kwh double,
    dcu_serial_number text,
    dt_name text,
    feeder_name text,
    instant_avgpf double,
    interval_datetime timestamp,
    lead_block_energy_kvarh double,
    md_block_sliding_type double,
    md_type double,
    mdas_datetime timestamp,
    mobile_no double,
    module_rtc double,
    neutral_current double,
    owner_name text,
    phase_current_l1 double,
    phase_current_l2 double,
    phase_current_l3 double,
    phase_voltage_l1 double,
    phase_voltage_l2 double,
    phase_voltage_l3 double,
    power_downtime_in_mins int,
    r_phase_active_power_kw double,
    status_byte double,
    subdevision_name text,
    substation_name text,
    y_phase_active_power_kw double,
    PRIMARY KEY (device_serial_number, interval_datetime)
) ;



#11 Delta LP CT
CREATE TABLE load_profile_data_ct (
    device_serial_number text,
    interval_datetime timestamp,
    avg_signal_strength double,
    b_phase_active_power_kw double,
    block_energy_kvah_export double,
    block_energy_kvah_import double,
    block_energy_kwh_export double,
    block_energy_kwh_import double,
    cumulative_energy_kvarh_q1 double,
    cumulative_energy_kvarh_q2 double,
    cumulative_energy_kvarh_q3 double,
    cumulative_energy_kvarh_q4 double,
    dcu_serial_number text,
    dt_name text,
    feeder_name text,
    lead_block_energy_kvarh double,
    mdas_datetime timestamp,
    owner_name text,
    phase_current_l1 double,
    phase_current_l2 double,
    phase_current_l3 double,
    phase_voltage_l1 double,
    phase_voltage_l2 double,
    phase_voltage_l3 double,
    power_downtime_in_mins int,
    r_phase_active_power_kw double,
    status_byte double,
    subdevision_name text,
    substation_name text,
    y_phase_active_power_kw double,
    PRIMARY KEY (device_serial_number, interval_datetime)
)

#12 Push Events Category
CREATE TABLE priority_events (
    owner_name text,
    created timestamp,
    created_by text,
    critical_event_list set<text>,
    high_priority_event_list set<text>,
    modified timestamp,
    non_critical_event_list set<text>,
    source text,
    updated_by text,
    PRIMARY KEY (owner_name)
)

#13
CREATE TABLE push_instant_threephase (
    device_serial_number text,
    meter_datetime timestamp,
    cum_export_kvah double,
    cum_export_kwh double,
    cum_import_kvah double,
    cum_import_kwh double,
    current_l1 double,
    current_l2 double,
    current_l3 double,
    device_id text,
    dt_name text,
    feeder_name text,
    mdas_datetime timestamp,
    owner_name text,
    pf_l1 double,
    pf_l2 double,
    pf_l3 double,
    subdivision_name text,
    substation_name text,
    voltage_l1 double,
    voltage_l2 double,
    voltage_l3 double,
    PRIMARY KEY (device_serial_number, meter_datetime)
) 
#14
CREATE TYPE gasCommandsLog(
    commandDatetime timestamp,
    commandName text,
    completionDatetime timestamp,
    retry int,
    seqNo int,
    status text
);
#15
CREATE TABLE non_dlms_gas_meter_command_logs (
    hesdate timestamp,
    gasmeterno text,
    batchid text,
    commandslist frozen <list<frozen <gascommandslog>>>,
    hesdatetime timestamp,
    ownername text,
    trackingid text,
    PRIMARY KEY (hesdate, gasmeterno)
);

#16
CREATE TABLE utility_master (
    i_am_id int,
    hes_owner_id text,
    email text,
    owner_name text,
    PRIMARY KEY (i_am_id, hes_owner_id)
)

#17
CREATE TABLE subdivisions_master (
    i_am_id int,
    hes_subdivision_id text,
    access set<text>,
    created timestamp,
    hes_owner_id text,
    latitude text,
    longitude text,
    modified timestamp,
    owner_name text,
    source text,
    subdivision_name text,
    updated_by text,
    user_id text,
    owner_id text,
    PRIMARY KEY (i_am_id, hes_subdivision_id)
)

#18
CREATE TABLE substations_master (
    i_am_id int,
    hes_substation_id text,
    access set<text>,
    created timestamp,
    hes_owner_id text,
    hes_subdivision_id text,
    latitude text,
    longitude text,
    modified timestamp,
    owner_name text,
    source text,
    subdivision_name text,
    substation_name text,
    updated_by text,
    user_id text,
    PRIMARY KEY (i_am_id, hes_substation_id)
)

#19
CREATE TABLE feeders_master (
    i_am_id int,
    hes_feeder_id text,
    access set<text>,
    created timestamp,
    feeder_name text,
    hes_subdivision_id text,
    hes_substation_id text,
    latitude text,
    longitude text,
    modified timestamp,
    owner_id text,
    owner_name text,
    source text,
    subdivision_name text,
    substation_name text,
    updated_by text,
    user_id text,
    PRIMARY KEY (i_am_id, hes_feeder_id)
)

#20
CREATE TABLE dt_trans_master (
    i_am_id int,
    dt_trans_id text,
    access set<text>,
    created timestamp,
    dt_name text,
    feeder_name text,
    hes_dt_trans_id text,
    hes_feeder_id text,
    hes_owner_id text,
    hes_subdivision_id text,
    hes_substation_id text,
    latitude text,
    longitude text,
    modified timestamp,
    owner_name text,
    source text,
    subdevision_name text,
    substation_name text,
    updated_by text,
    user_id text,
    owner_id text,
    PRIMARY KEY (i_am_id, dt_trans_id)
)
#21
CREATE TABLE dcu_info (
    dcu_serial_number text,
    dcu_mac_nic_id text,
    frequency double,
    ipv6_address text,
    latitude text,
    longitude text,
    manufacturer text,
    network text,
    owner text,
    remarks text,
    sim_no text,
    PRIMARY KEY (dcu_serial_number)
)
#22
CREATE TABLE dcu_master_logs (
    dcu_serial_number text,
    creation_date timestamp,
    created_by text,
    created_datetime timestamp,
    dcu_mac_nic_id text,
    deleted_by text,
    deleted_datetime timestamp,
    frequency double,
    ipv6_address text,
    latitude text,
    longitude text,
    manufacturer text,
    network text,
    remarks text,
    sim_no text,
    updated_by text,
    updated_datetime timestamp,
    PRIMARY KEY (dcu_serial_number, creation_date)
) 